// rosetta-ai-sdk/src/types/openai.types.ts

import { RosettaToolCallRequest } from './common.types'

/**
 * The function that the model called.
 */
export interface OpenAICompletionFunctionCall {
  name: string
  arguments: string
}

/**
 * The tool calls generated by the model, such as function calls.
 */
export interface OpenAICompletionToolCall {
  id: string
  type: 'function'
  function: OpenAICompletionFunctionCall
}

/**
 * A chat completion message generated by the model.
 */
export interface OpenAICompletionMessage {
  role: 'assistant'
  content: string | null
  tool_calls?: OpenAICompletionToolCall[]
  refusal?: string | null
}

/**
 * Log probability information for a token.
 */
export interface Logprob {
  token: string
  logprob: number
  bytes: number[] | null
  top_logprobs: Array<{
    token: string
    logprob: number
    bytes: number[] | null
  }>
}

/**
 * Log probability information for the choice.
 */
export interface Logprobs {
  content: Logprob[] | null
  refusal?: Logprob[] | null
}

/**
 * A single choice in the chat completion.
 */
export interface OpenAICompletionChoice {
  index: number
  message: OpenAICompletionMessage
  logprobs: Logprobs | null
  finish_reason: 'stop' | 'length' | 'content_filter' | 'tool_calls' | string | null
}

/**
 * Breakdown of tokens used in the prompt.
 */
export interface PromptTokenDetails {
  cached_tokens?: number
  audio_tokens?: number
}

/**
 * Breakdown of tokens used in a completion.
 */
export interface CompletionTokenDetails {
  reasoning_tokens?: number
  audio_tokens?: number
  accepted_prediction_tokens?: number
  rejected_prediction_tokens?: number
}

/**
 * Usage statistics for the completion request.
 */
export interface OpenAICompletionUsage {
  prompt_tokens: number
  completion_tokens: number
  total_tokens: number
  prompt_tokens_details?: PromptTokenDetails
  completion_tokens_details?: CompletionTokenDetails
}

/**
 * The top-level Chat Completion object, conforming to the OpenAI specification.
 */
export interface OpenAICompletion {
  id: string
  object: 'chat.completion'
  created: number
  model: string
  choices: OpenAICompletionChoice[]
  usage: OpenAICompletionUsage
  system_fingerprint: string | null
  service_tier?: string | null
}
